content:
  source:
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/node_exporter.git
    specfile: golang-github-prometheus-node_exporter.spec
name: golang-github-prometheus-node_exporter
owners:
- pgier@redhat.com
