content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        target: release-3.11
      url: git@github.com:openshift/node_exporter.git
enabled_repos:
- rhel-server-ose-rpms
from:
  stream: rhel
labels:
  License: GPLv2+
  io.k8s.description: Prometheus exporter for hardware and OS metrics exposed by *NIX
    kernels, written in Go with pluggable metric collectors
  io.k8s.display-name: Node Exporter
  io.openshift.tags: openshift,node
  vendor: Red Hat
name: openshift3/prometheus-node-exporter
owners: []
