content:
  source:
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/prometheus.git
    specfile: golang-github-prometheus-prometheus.spec
name: golang-github-prometheus-prometheus
owners:
- kgeorgie@redhat.com
- pgier@redhat.com
- spasquie@redhat.com
